BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET
BloggerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET
BloggerBlogBundle_blog_show:
    path:   /{id}
    defaults: { _controller: "BloggerBlogBundle:Blog:show" }
    requirements:
        methods:  GET
        id: \d+
BloggerBlogBundle_allcategoryes:
    path:    /{id}
    defaults: { _controller: "BloggerBlogBundle:Category:index" }
    requirements:
        methods:  GET
        id: \d+
BloggerBlogBundle_allblogs:
    path:     category/{id}
    defaults: { _controller: "BloggerBlogBundle:Category:categoryshow" }
    requirements:
         methods:  GET
         id: \d+