BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET
BloggerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET
BloggerBlogBundle_blog_show:
    path:  /{id}
    defaults: { _controller: "BloggerBlogBundle:Blog:show" }
    requirements:
        methods:  GET
        id: \d+
BloggerBlogBundle_category_show:
    path:  /{id}
    defaults: { _controller: "BloggerBlogBundle:Category:show" }
    requirements:
        methods:  GET
        id: \d+